AllCops:
  RunRailsCops: true
  Exclude:
    - 'db/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'spec/**/*'
    - 'bin/**/*'
    - 'log/**/*'


Style/AlignHash:
  # table - left alignment of keys, hash rockets, and values
  #   'a'  => 2
  #   'bb' => 3
  EnforcedHashRocketStyle: table
  # table - left alignment of keys and values
  #   a:  0
  #   bb: 1
  EnforcedColonStyle: key

  EnforcedLastArgumentHashStyle: always_inspect
  SupportedLastArgumentHashStyles:
    - always_inspect
    - always_ignore
    - ignore_implicit
    - ignore_explicit

Style/ClassAndModuleChildren:
  # `compact` - combine definitions as much as possible
  #   class Foo::Bar
  #   end
  #
  # The compact style is only forced, for classes / modules with one child.
  EnforcedStyle: compact

# Prefer :sym => value syntax
Style/HashSyntax:
  EnforcedStyle: hash_rockets
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 250

Metrics/ClassLength:
  Max: 500

Metrics/AbcSize:
  Max: 500

Metrics/CyclomaticComplexity:
  Max: 500

Metrics/PerceivedComplexity:
  Max: 500
    
Metrics/MethodLength:
  Max: 100
